### PR TITLE
fix: Prevent variable names clashing when defining multiple Commands in schema

### LINKED ISSUE #132: Defining multiple commands in the schema creates a variable name collision
Excerpt from affected generation, using v0.0.4-a07:

```
#region Commands
            var hasBuffer = entityManager.HasComponent<ApplyDamage>(entity);
            if (!hasBuffer)
            {
                entityManager.AddBuffer<ApplyDamage>(entity);
            }
            var hasRequestBuffer = entityManager.HasComponent<ApplyDamageRequest>(entity);
            if (!hasRequestBuffer)
            {
                entityManager.AddBuffer<ApplyDamageRequest>(entity);
            }
            var hasBuffer = entityManager.HasComponent<ApplyScore>(entity);
            if (!hasBuffer)
            {
                entityManager.AddBuffer<ApplyScore>(entity);
            }
            var hasRequestBuffer = entityManager.HasComponent<ApplyScoreRequest>(entity);
            if (!hasRequestBuffer)
            {
                entityManager.AddBuffer<ApplyScoreRequest>(entity);
            }
#endregion
```

**[Estimate: Half a day]**

### PR DESCRIPTION
**Pull request by eriksvedang**
Closes #132.

This solution does not use functions (mentioned as a possible solution in #132) since that would require generics (which we try to avoid, no?) Instead, it creates a block for each Command: ```{ command1 } {command2 } etc```

If someone would rather like to see the generics approach, please tell me and I'll adjust the PR :)

### CODE REVIEW

**Comment by frarees** [comment]
I like the block scope, it won't change the IL a bit, so no further implications 👍

**Comment by rpadrela** [comment]
Are generics like templates in C++?

Is there a particular reason as to why we avoid them?

**Review by tadej — APPROVED** [review]
Looks good to me.

**Comment by tadej** [comment]
Generics are kind of like templates in C++, albeit a bit less powerful afaik (see below).
I'd love to discuss some reasons to avoid using them as well (I don't have any immediate concerns about using them).

_The C++ compiler is smart enough to compile the code only once for any given set of template arguments, but it isn’t able to share code in the way that the CLR does with reference types. That lack of sharing does have its benefits, though—it allows type specific optimizations, such as inlining method calls for some type parameters but not others, from the same template. It also means that overload resolution can be performed separately for each set of type parameters, rather than just once based solely on the limited knowledge the C# compiler has due to any constraints present.

One significant feature that C++ templates have over C# generics is that the template arguments don’t have to be type names. Variable names, function names, and constant expressions can be used as well. A common example of this is a buffer type that has the size of the buffer as one of the template arguments—a buffer will always be a buffer of 20 integers, and a bufferwill always be a buffer of 35 doubles. This ability is crucial to template metaprogramming (see the Wikipedia article, http://en.wikipedia.org/wiki/Template_metaprogramming), which is an advanced C++ technique, the very idea of which scares me but that can be powerful in the hands of experts.

C++ templates are more flexible in other ways too. They don’t suffer from the lack of operator constraints and there are a few other restrictions that don’t exist in C++: you can derive a class from one of its type parameters, and you can specialize a template for a particular set of type arguments. The latter ability allows the template author to write general code to be used when there’s no more knowledge available, and specific (often highly optimized) code for particular types._

**Comment by cbrisebois** [comment]
I don't think there are really strong reasons to avoid generic in C#.  They
can even be helpful to avoid boxing/unboxing.

**Comment by gamedolphin** [comment]
One of the main reasons to avoid generics is to keep our code "burstable" since burst still doesn't have support for generics.

**Comment by frarees** [comment]
@gamedolphin any docs or articles on burst being a bad practice or incompatible with generics? AFAIK generics are used widely on DOTS, and everything is burstable there. Not only it's recommended but it's the sanest way to get performant code without too much hassle. What seems to be forbidden in burstland is interfaces and delegates.

From [this article](https://www.jacksondunstan.com/articles/5380):

> Not only is it possible to write generic algorithms in Burst-compiled code, but all of this abstraction ends up being totally free from a performance perspective. It’s not quite as friendly as using lambdas, but readability and code reuse are much improved over manually copying the algorithm into every job type.

**Comment by piot** [comment]
Generics is slower, doesn't work with Unity ECS (if not fixed recently) in all cases and there is no real benefit in using them in a generated source file.

**Comment by piot** [comment]
My suggestion, as always, look at the big picture. Don't over engineer something, please just fix a super simple bug.

**Comment by eriksvedang** [comment]
Thanks for the feedback everyone!! I feel confident merge:ing this as-is since at least it doesn't make things slow, which is what matters most to our customers in the end I think. Having auto-generated code be a bit messy or verbose isn't such a big deal since it's still abstracted away in the code generator. I would like to know more about the various claims regarding benefits and drawbacks with C#:s generics though, so I'll read up on that at some point.

**Pull request merged**
