### PR TITLE
fix: commands not working

### PR DESCRIPTION
**Pull request by rpadrela**
Unity was not instantiating an object of DetectCommandsSentSystem because the class was not providing a default constructor. Removed only constructor and added a BootUp() method similar to SyncSendSystem and other classes.

Removed the use of a DebugOutBitStream which was causing the server to crash when deserializing the data serialized through this type of stream.

### CODE REVIEW

**Comment by eriksvedang** [comment]
Cool, I'll take this for a spin!

**Review by eriksvedang — APPROVED** [review]
Looks great. This was due to my change, I did not think about the implications of changing the constructor. I'll look through the other systems to make sure I did not break any more of them.

**Comment by rpadrela** [comment]
> Looks great. This was due to my change, I did not think about the implications of changing the constructor. I'll look through the other systems to make sure I did not break any more of them.

There was a warning about the class not providing a default constructor but it was buried under a bazillion of other warnings. I guess this proves how important it is to have a 0 warning policy. :)

**Comment by eriksvedang** [comment]
@rpadrela Yeah, for sure!

**Pull request merged**
